### ISSUE TITLE
Platform hosting requirements

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/openlocal#29]
What hosting platform requirements are there for an OL site?

**Comment by pmackay** [comment]
Why? Is this question about cost or the technical requirements?

**Comment by GilesGibson** [comment]
Both. Need to know what the requirements are for a typical hosting site for a start-up web site. Low traffic to start with, able to move to a faster platform as traffic develops.

**Comment by pmackay** [comment]
Well if you want basic hosting costs we can put it on £10/month account with a regular hosting provider. But that doesnt cover management costs. It may get slow depending on traffic. Pantheon is $25/month and of course takes away a lot of the management costs because its a more advanced hosting system.

Why do you want to know tech requirements? Its basically PHP, MySQL, Apache, etc.

**Comment by pmackay** [comment]
Was this last answer sufficient?

**Comment by GilesGibson** [comment]
We need to pass this over to CP neighbours, it is their call.

**Comment by pmackay** [comment]
Really CP need to be able to cover Pantheon hosting costs, otherwise managing a Drupal site prohibitve.
