### ISSUE TITLE
Replace Place type with Location

### ISSUE THREAD

**Issue by pmackay** [folklabs/openlocal#7]
This one is more straightforward, however can I check:
- Is Places a better term to use on the site for users? Should the list and map pages showing locations still be called Places? Or change to Locations? 
- Any thoughts on whether the page layout should be changed/improved?

@djwesto @GilesGibson

**Comment by GilesGibson** [comment]
I would probably vere towards location. 

@pmackay what page layout are you referring to?

**Comment by djwesto** [comment]
This is the sort of thing I'd love to test but, in the absence of testing, I suppose we need to make a decision. _Location_ feels more precise to me whereas _Place_ feels more user-friendly. Presumably, @pmackay, we need to select a word and stick with it because it becomes part of the system?

I actually agree with @GilesGibson and think that _Location_ works a bit better because it suggests that (at some time in future) we'll offer users the chance to add Locations – i.e. geolocations which aren't currently considered a "Place" – growing plots like the Edible Bus Stop might be one good example of a Location which people might not consider a "Place" (yet). Asset mapping is another good example of this.

So my vote goes to Location. @pmackay, what are your thoughts?

**Comment by pmackay** [comment]
This page http://www.hernehill.org.uk/places is currently not well themed
at all and a bit broken (map shouldnt have a paginate). But should it be
something very different?

**Comment by pmackay** [comment]
I'm fine with Location(s), it keeps type and UI consistent.

**Comment by GilesGibson** [comment]
We have just had added to the site a place/location/venue that is at the edge of the park - part of an initiative for a rain garden. An example of a nebulous asset that hadn't been identified before. Now, via Connecting Communities everyone will be able to find a raingarden.

**Comment by GilesGibson** [comment]
I can add to a list of things that should happen on the map page if you want. It really needs some work done, as you say.

**Comment by djwesto** [comment]
I agree the current Places page is probably not meeting our needs. Here are a few thoughts:
- When you decide how you might refactor the control buttons, we'd probably want to include a button to add new Locations.
- Would we also offer a button or view to show just "My Locations" or "Locations I've added"?
- What do you think of splitting the two views into separate tabs so we could have a map on one page along with a second tab to offer a _Location Listing_ view?
- Separating the views in this way would allow you to have pagination on the listing view as well, should we wish to keep this.
- What do you think about offering filters on places or any other means of sorting or filtering - perhaps only on the listing view?
- Longer term (@pmackay, don't hit me for asking this but...) could you "Follow" a place to get updates on all the events that are happening there and any related news stories etc?

**Comment by pmackay** [comment]
@GilesGibson your thoughts on list v map, and whether separate tabs would be better?
